### ISSUE TITLE
[Q] What's the purpose of require_bw_ member variable for DPE class?

### ISSUE THREAD

**Issue by hyoklee** [HDFGroup/hermes#457]
round_robin.cc sets it false.

```
  if (bandwidths.size()) {
    require_bw_ = false;
  }
```

However, I don't see it being used anywhere else.

**Comment by lukemartinlogan** [comment]
Thank you for catching this; this was part of an optimization which I made and then removed when I was updating the DPE.

The original intention of require_bw_ was that each inherited class would set this member as either true or false in its constructor. If true, the DPE would make a metadata call to get all bandwidths in the system and pass those bandwidths as a parameter to the specific DPE. 

round_robin.cc and random.cc originally set this value to false in their constructor, whereas the minimize_io_time DPE set it to true.

In this specific file, I added this code simply because I didn't want to run into compiler problems due to the fact that RoundRobin does not actually use the bandwidths input. This code could be replaced simply with (void) bandwidths instead.
